export const keyMap = {
  rrd_id: '№',
  gi_id: 'Номер поставки',
  subject_name: 'Предмет',
  nm_id: 'Код номенклатуры',
  brand_name: 'Бренд',
  sa_name: 'Артикул поставщика',
  ts_name: 'Размер',
  barcode: 'Баркод',
  doc_type_name: 'Тип документа',
  supplier_oper_name: 'Обоснование для оплаты',
  order_dt: 'Дата заказа покупателем',
  sale_dt: 'Дата продажи',
  quantity: 'Кол-во',
  retail_price: 'Цена розничная',
  retail_amount: 'Вайлдберриз реализовал Товар (Пр)',
  product_discount_for_report: 'Согласованный продуктовый дисконт, %',
  supplier_promo: 'Промокод %',
  sale_percent:
    'Итоговая согласованная скидка' || 'Итоговая согласованная скидка, %',
  // sale_percent: "Итоговая согласованная скидка, %",
  retail_price_withdisc_rub: 'Цена розничная с учетом согласованной скидки',
  sup_rating_prc_up: 'Размер снижения кВВ из-за рейтинга, %',
  is_kgvp_v2: 'Размер снижения кВВ из-за акции, %',
  ppvz_spp_prc:
    'Скидка постоянного Покупателя (СПП)' ||
    'Скидка постоянного Покупателя (СПП), %',
  // ppvz_spp_prc: "Скидка постоянного Покупателя (СПП), %",
  commission_percent: 'Размер кВВ, %',
  ppvz_kvw_prc_base:
    'Размер кВВ без НДС, % Базовый' || 'Размер  кВВ без НДС, % Базовый',
  // ppvz_kvw_prc_base: "Размер  кВВ без НДС, % Базовый",
  ppvz_kvw_prc: 'Итоговый кВВ без НДС, %',
  ppvz_sales_commission:
    'Вознаграждение с продаж до вычета услуг поверенного, без НДС',
  ppvz_reward: 'Возмещение за выдачу и возврат товаров на ПВЗ',
  acquiring_fee: 'Возмещение издержек по эквайрингу',
  ppvz_vw: 'Вознаграждение Вайлдберриз (ВВ), без НДС',
  ppvz_vw_nds: 'НДС с Вознаграждения Вайлдберриз',
  ppvz_for_pay: 'К перечислению Продавцу за реализованный Товар',
  delivery_amount: 'Количество доставок',
  return_amount: 'Количество возврата',
  delivery_rub: 'Услуги по доставке товара покупателю',
  penalty: 'Общая сумма штрафов',
  additional_payment: 'Доплаты',
  bonus_type_name: 'Виды логистики, штрафов и доплат',
  acquiring_bank: 'Наименование банка-эквайера',
  ppvz_office_id: 'Номер офиса',
  ppvz_office_name: 'Наименование офиса доставки',
  ppvz_inn: 'ИНН партнера',
  ppvz_supplier_name: 'Партнер',
  office_name: 'Склад',
  gi_box_type_name: 'Тип коробов',
  declaration_number: 'Номер таможенной декларации',
  shk_id: 'ШК',
  rid: 'Rid',
  srid: 'Srid',
  rebill_logistic_cost: 'Возмещение издержек по перевозке',
  rebill_logistic_org: 'Организатор перевозки',
  site_country: 'Страна',
  date_to: 'Конечная дата отчета',
  date_from: 'Начальная дата отчета',
  realizationreport_id: 'Номер отчёта',
  create_dt: 'Дата формирования отчёта',
  currency_name: 'Валюта отчёта',
  ppvz_supplier_id: 'Номер партнера',
  storage_fee: 'Хранение',
  deduction: 'Удержания',
  acceptance: 'Платная приемка',
  sticker_id: 'Стикер МП',
};
export const keyMapReverse = {
  '№': 'rrd_id',
  'Номер поставки': 'gi_id',
  Предмет: 'subject_name',
  'Код номенклатуры': 'nm_id',
  Бренд: 'brand_name',
  'Артикул поставщика': 'sa_name',
  Размер: 'ts_name',
  Баркод: 'barcode',
  'Тип документа': 'doc_type_name',
  'Обоснование для оплаты': 'supplier_oper_name',
  'Дата заказа покупателем': 'order_dt',
  'Дата продажи': 'sale_dt',
  'Кол-во': 'quantity',
  'Цена розничная': 'retail_price',
  'Вайлдберриз реализовал Товар (Пр)': 'retail_amount',
  'Согласованный продуктовый дисконт, %': 'product_discount_for_report',
  'Промокод %': 'supplier_promo',
  'Итоговая согласованная скидка': 'sale_percent',
  'Итоговая согласованная скидка, %': 'sale_percent',
  'Цена розничная с учетом согласованной скидки': 'retail_price_withdisc_rub',
  'Размер снижения кВВ из-за рейтинга, %': 'sup_rating_prc_up',
  'Размер снижения кВВ из-за акции, %': 'is_kgvp_v2',
  'Скидка постоянного Покупателя (СПП)': 'ppvz_spp_prc',
  'Скидка постоянного Покупателя (СПП), %': 'ppvz_spp_prc',
  'Размер кВВ, %': 'commission_percent',
  'Размер кВВ без НДС, % Базовый': 'ppvz_kvw_prc_base',
  'Размер  кВВ без НДС, % Базовый': 'ppvz_kvw_prc_base',
  'Итоговый кВВ без НДС, %': 'ppvz_kvw_prc',
  'Вознаграждение с продаж до вычета услуг поверенного, без НДС':
    'ppvz_sales_commission',
  'Возмещение за выдачу и возврат товаров на ПВЗ': 'ppvz_reward',
  'Возмещение издержек по эквайрингу': 'acquiring_fee',
  'Вознаграждение Вайлдберриз (ВВ), без НДС': 'ppvz_vw',
  'НДС с Вознаграждения Вайлдберриз': 'ppvz_vw_nds',
  'К перечислению Продавцу за реализованный Товар': 'ppvz_for_pay',
  'Количество доставок': 'delivery_amount',
  'Количество возврата': 'return_amount',
  'Услуги по доставке товара покупателю': 'delivery_rub',
  'Общая сумма штрафов': 'penalty',
  Доплаты: 'additional_payment',
  'Виды логистики, штрафов и доплат': 'bonus_type_name',
  'Наименование банка-эквайера': 'acquiring_bank',
  'Номер офиса': 'ppvz_office_id',
  'Наименование офиса доставки': 'ppvz_office_name',
  'ИНН партнера': 'ppvz_inn',
  Партнер: 'ppvz_supplier_name',
  Склад: 'office_name',
  'Тип коробов': 'gi_box_type_name',
  'Номер таможенной декларации': 'declaration_number',
  ШК: 'shk_id',
  Rid: 'rid',
  Srid: 'srid',
  'Возмещение издержек по перевозке': 'rebill_logistic_cost',
  'Организатор перевозки': 'rebill_logistic_org',
  Страна: 'site_country',
  'Конечная дата отчета': 'date_to',
  'Начальная дата отчета': 'date_from',
  'Номер отчёта': 'realizationreport_id',
  'Дата формирования отчёта': 'create_dt',
  'Валюта отчёта': 'currency_name',
  'Номер партнера': 'ppvz_supplier_id',
  Хранение: 'storage_fee',
  Удержания: 'deduction',
  'Платная приемка': 'acceptance',
  'Стикер МП': 'sticker_id',
};
